#!/usr/bin/env bash
# Launch the DaMiao motor dashboard.
#
# The CAN adapter on this machine is a candleLight/gs_usb device (USB id
# 1d50:606f) which the kernel exposes as SocketCAN interfaces (can0/can1), NOT a
# DaMiao DM-USB2FDCAN in USB mode (vendor 34b7). So the dashboard talks to it
# through motorbridge's SocketCAN-FD transport. Override DM_DEVICE_TYPE /
# DM_CHANNEL if you actually have a DaMiao USB adapter instead.
set -euo pipefail
cd "$(dirname "$0")"

# Transport: SocketCAN-FD over the gs_usb adapter, scanning both channels.
export DM_DEVICE_TYPE="${DM_DEVICE_TYPE:-socketcanfd}"
export DM_CHANNEL="${DM_CHANNEL:-can0,can1}"
# CAN-FD bitrates (DaMiao default: 1 Mbit nominal / 5 Mbit data).
CAN_BITRATE="${CAN_BITRATE:-1000000}"
CAN_DBITRATE="${CAN_DBITRATE:-5000000}"

# Point the DaMiao DM_Device SDK at the runtime fetched by
# `motorbridge-install-dm-device --download` (cached in ~/.cache). Only needed
# for the DM_Device (USB-mode) transport, harmless otherwise.
LIB="$HOME/.cache/motorbridge/dm_device/v1.1.0/linux/x86_64/libdm_device.so"
if [ -f "$LIB" ]; then
  export MOTOR_DM_DEVICE_LIB="$LIB"
fi

# Bring any SocketCAN interface we intend to use UP first. A SocketCAN bus must
# be configured + UP before motorbridge can open it; doing it here means a fresh
# plug-in "just works" without remembering the ip-link incantation.
if [ "${DM_DEVICE_TYPE}" = "socketcanfd" ] || [ "${DM_DEVICE_TYPE}" = "socketcan" ]; then
  IFS=',' read -ra _CAN_IFACES <<< "$DM_CHANNEL"
  for iface in "${_CAN_IFACES[@]}"; do
    iface="$(echo "$iface" | tr -d '[:space:]')"
    [ -z "$iface" ] && continue
    if ! ip link show "$iface" >/dev/null 2>&1; then
      echo "WARNING: SocketCAN interface '$iface' not found (is the USB-CAN adapter plugged in?)" >&2
      continue
    fi
    if ip link show "$iface" | grep -q "state UP"; then
      continue
    fi
    echo "Bringing up $iface (bitrate ${CAN_BITRATE}, dbitrate ${CAN_DBITRATE}, fd on)..."
    sudo ip link set "$iface" type can bitrate "$CAN_BITRATE" \
      dbitrate "$CAN_DBITRATE" fd on
    sudo ip link set "$iface" up
  done
fi

# Bind to all interfaces by default so the dashboard is reachable from other
# machines on the LAN (override HOST=127.0.0.1 to keep it local-only).
export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-5000}"

# HTTPS: serve over TLS using a certificate chain (CA + server leaf).
# Set MOTOR_HTTP=1 to skip this and serve plain HTTP instead.
#
# By default we PREFER the certificate generated by the Camera-SensorPortal
# (Spyglass) tooling so its ca.crt — the file you install on other devices —
# matches the leaf this dashboard presents. The portal cert's SAN already covers
# this host's LAN IPs, so it's valid for the dashboard too. Override the location
# with PORTAL_CERTS_DIR, or point MOTOR_CERT/MOTOR_KEY at any cert directly. If no
# portal cert exists we fall back to generating a local one in certs/.
PORTAL_CERTS_DIR="${PORTAL_CERTS_DIR:-$HOME/Camera-SensorPortal/certs}"
if [ "${MOTOR_HTTP:-0}" != "1" ]; then
  if [ -z "${MOTOR_CERT:-}" ] && [ -z "${MOTOR_KEY:-}" ]; then
    if [ -f "$PORTAL_CERTS_DIR/server.crt" ] && [ -f "$PORTAL_CERTS_DIR/server.key" ]; then
      export MOTOR_CERT="$PORTAL_CERTS_DIR/server.crt"
      export MOTOR_KEY="$PORTAL_CERTS_DIR/server.key"
      echo "Using portal certificate: $MOTOR_CERT"
      echo "  -> install $PORTAL_CERTS_DIR/ca.crt as a trusted CA on other devices"
    elif [ ! -f certs/server.crt ] || [ ! -f certs/server.key ]; then
      echo "No portal cert at $PORTAL_CERTS_DIR and no local cert; generating one (certs/)..."
      echo "  (tip: run 'make cert' in Camera-SensorPortal to use that cert instead)"
      ./gen_cert.sh
    fi
  fi
  SCHEME="https"
else
  # Tell app.py to skip the cert even if a cert exists.
  export MOTOR_CERT="/nonexistent"
  export MOTOR_KEY="/nonexistent"
  SCHEME="http"
fi

echo "Transport: $DM_DEVICE_TYPE  channel(s): $DM_CHANNEL"
echo
echo "Open the dashboard at:"
echo "  ${SCHEME}://localhost:$PORT            (on this machine)"
for ip in $(hostname -I 2>/dev/null); do
  case "$ip" in
    *:*) ;;  # skip IPv6
    *) echo "  ${SCHEME}://${ip}:$PORT   <- give this to other devices" ;;
  esac
done
if [ "$SCHEME" = "https" ]; then
  # Point users at the ca.crt that matches whichever leaf we're serving.
  if [ "${MOTOR_CERT:-}" = "$PORTAL_CERTS_DIR/server.crt" ]; then
    CA_HINT="$PORTAL_CERTS_DIR/ca.crt"
  else
    CA_HINT="certs/ca.crt"
  fi
  echo
  echo "Self-signed cert: accept the browser warning once, or install"
  echo "$CA_HINT as a trusted CA on the client to remove it."
fi
echo
exec ./venv/bin/python app.py
